### ISSUE TITLE
Create the hello-world

### ISSUE THREAD

**Issue by JuliaGlocka** [JuliaGlocka/api-eventlogger#1]

**Comment by holms** [comment]
- [ ] Use separate branch for hellworld app with name `feat/1/helloworld`, we'll merge after ticket will be finished. 
- [ ] Don't merge the branch after ticket will be finished. I'll show you how to use `git rebase`.

**Comment by holms** [comment]
This branch is spoiled. This branch contains irrelevant files. 

- [x] Backup files from this branch somewhere else
- [x] Go to master branch remove compose.yaml. We don't need it.
- [x] requirement.txt should not present in master branch, delete it. it should be in this branch only
- [x] Delete feat/1/helloworld branch from this repo
- [x] Create feat/1/helloworld from master
- [x] Copy `app.py` and `requirements.txt` from your backuped up branch to this new branch
- [x] Make a simple commit also mention this ticket in commit description: 
```
git add .
git commit -m "add helloworld app" -m "affect #1"
```

**Comment by holms** [comment]
What's the point of this commit :)? https://github.com/JuliaGlocka/api-eventlogger/commit/54faea09826a568c6901556847a94c8aea4321d9 

Which of above bullet points sounds confusing?

**Comment by JuliaGlocka** [comment]
Well, I though that helloworld.py should be on feat/1/helloworld branch. Actually none of these bullets. But if I misunderstand them, maybe there is a way for me to get the bigger scope, like description of what needs to be put where at the end, like such and such files on this repo on this branch
