### ISSUE TITLE
create Dockerfile

### ISSUE THREAD

**Issue by holms** [JuliaGlocka/api-eventlogger#3]
- [ ] Create Dockerfile using python alpine image - https://docs.docker.com/compose/gettingstarted/

**Comment by JuliaGlocka** [comment]
@holms I have edited the Dockerfile in the api-eventlogger repository. Pls check

**Comment by holms** [comment]
Cherrypy will be used in api-fbanalyze project. API-eventlogger will be using flask framework. 

Also probably makes sense to do hello world tasks first because Dockerfile will fail to build docker image.

**Comment by holms** [comment]
Also avoid using dashes in file names, underscore is more conventional symbol for splitting words. 
Instead  of `./back-end` I recommend `/app` or `/src` or `/www`

Check the default port of flask, so you'd know which port to expose.

Make sure that docker is building docker image successfully with this  Dockerfile before committing it to the repo 

Remove compose.yaml from this repo, it belongs in sdk-fbanalyze. Or just move it there for now.

**Comment by holms** [comment]
Also I'd move `Dockerfile` to a branch `feat/3/dockerfile` for now, as we need to fix many stuff currently, let's not trash the main branch with unnecessary stuff.

- [x] This ticket should be finished and reviewed before working with Dockerfile: #1 
- [x] So delete Dockerfile in main branch `git rm -f Dockerfile`, commit it with message "remove Dockerfile". If you want to commits to be visible in this ticket do two message "git commit -m "remove Dockerfile" -m "affects #<ticketnumber>"
- [x] Create a branch `feat/3/dockerfile`
- [x] Create a Dockerfile and test that it works by building docker image
- [x] Launch docker container using freshly built docker image and test if the port which you've exposed works.

In the future such plan of works should be done by yourself, but for now I'll guide you step-by-step so you' get familiar with a workflow.
